apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: nginx-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
