---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-south-1
  version: "1.18"

availabilityZones: ["ap-south-1a", "ap-south-1b", "ap-south-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 1
  instanceType: t3.medium
  ssh:
    enableSsm: true

fargateProfiles:
  - name: game-2048
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: game-2048
      
# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:ap-south-1:661506585234:key/b979e370-2ffe-4fd2-a5b3-4a391a743435
