# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: game-2048

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: php-apache
spec:
  type: ClusterIP
  selector:
    run: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: game-2048
#   name: php-apache
#   labels:
#     run: php-apache
# spec:
#   ports:
#   - port: 80
#   selector:
#     run: php-apache
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   namespace: game-2048
#   name: php-apache
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: php-apache
#               servicePort: 80

